[package]
name = "bagua-net"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.10"
tracing = "0.1"
tracing-subscriber = "0.2"
thiserror = "1"
