[package]
name = "bagua-net"
version = "0.1.0"
authors = ["shjwudp"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nix = "0.22.0"
tracing = "0.1"
tracing-subscriber = "0.2"
thiserror = "1"
bytes = "0.4"
libc = "0.2"
ffi-convert = "0.5"
